In [1]:
import numpy as np

nums = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
letters = np.array(['a', 'b', 'c', 'd', 'a', 'e', 'b'])

In [2]:
a = True

In [3]:
b = 5 > 7
print(b)

False


In [4]:
less_then_5 = nums < 5
less_then_5

array([ True,  True,  True,  True, False, False, False, False, False,
       False])

In [5]:
pos_a = letters == 'a'
pos_a

array([ True, False, False, False,  True, False, False])

In [6]:
less_then_5 = nums < 5
less_then_5

array([ True,  True,  True,  True, False, False, False, False, False,
       False])

In [7]:
nums[less_then_5]

array([1, 2, 3, 4])

In [8]:
m = np.matrix('1 2 3 4; 5 6 7 8; 9 1 5 7')
print(m)

[[1 2 3 4]
 [5 6 7 8]
 [9 1 5 7]]


In [11]:
mod_m = np.logical_and(m>=3, m<=7)
mod_m

matrix([[False, False,  True,  True],
        [ True,  True,  True, False],
        [False, False,  True,  True]])

In [12]:
m[mod_m]

matrix([[3, 4, 5, 6, 7, 5, 7]])

In [13]:
nums = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
nums[nums < 5]

array([1, 2, 3, 4])

In [14]:
nums[nums < 5] = 10
print(nums)

[10 10 10 10  5  6  7  8  9 10]


In [15]:
m[m > 7] = 25
print(m)

[[ 1  2  3  4]
 [ 5  6  7 25]
 [25  1  5  7]]
