# Индивидуальное задание №1

## Элемент матрицы называется локальным минимумом, если он строго меньше всех имеющихся у него соседей. Подсчитать количество локальных минимумов заданной матрицы размером 10 на 10. Найти сумму модулей элементов, расположенных выше главной диагонали.

In [1]:
import numpy as np

# Создаем матрицу размером 10 на 10
matrix = np.random.randint(0, 100, (10, 10))

In [2]:
# Определяем локальные минимумы
is_local_min = np.logical_and(matrix[1:] > matrix[:-1], matrix[:-1] < matrix[1:])
local_min_count = np.count_nonzero(is_local_min)

In [3]:
# Считаем сумму модулей элементов выше главной диагонали
sum_above_diag = np.sum(np.abs(np.triu(matrix, k=1)))

In [4]:
print(f"Количество локальных минимумов: {local_min_count}")
print(f"Сумма модулей элементов выше главной диагонали: {sum_above_diag}")

Количество локальных минимумов: 39
Сумма модулей элементов выше главной диагонали: 2139


In [5]:
print(matrix)

[[11 61 83 76 65  0 49 51 62 95]
 [60 33 41 52 25 88 27 41 17 54]
 [70 96 30 12  3 34 48 23 28  9]
 [61 87 13 62 84 94 55 73 42 78]
 [62 32 24  1 45 12 40 26 92  4]
 [37 11 75 73 92  7 31 44  7 63]
 [29 47 78  1 55 11 98 55 91 48]
 [78 78 77 59 24 44 40 65 74 44]
 [39 96 43 98  8 94 64 59 94 38]
 [39 29 30 36 50 91 68 21 42 32]]
